//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Site1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site1.Master", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на парола.
        /// </summary>
        internal static string btnlinkChangePassResource1_Text {
            get {
                return ResourceManager.GetString("btnlinkChangePassResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string btnlinkChangePassResource1_ToolTip {
            get {
                return ResourceManager.GetString("btnlinkChangePassResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        internal static string ChangePassword1Resource1_CancelButtonText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Променете парола.
        /// </summary>
        internal static string ChangePassword1Resource1_ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect or New Password invalid. New Password length minimum: {0}. Non-alphanumeric characters required: {1}..
        /// </summary>
        internal static string ChangePassword1Resource1_ChangePasswordFailureText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ChangePasswordFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на парола.
        /// </summary>
        internal static string ChangePassword1Resource1_ChangePasswordTitleText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ChangePasswordTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърди нова парола:.
        /// </summary>
        internal static string ChangePassword1Resource1_ConfirmNewPasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ConfirmNewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърди нова парола трябва да съвпада с Нова парола..
        /// </summary>
        internal static string ChangePassword1Resource1_ConfirmPasswordCompareErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ConfirmPasswordCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване на новата парола е задължително..
        /// </summary>
        internal static string ChangePassword1Resource1_ConfirmPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ConfirmPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължете.
        /// </summary>
        internal static string ChangePassword1Resource1_ContinueButtonText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_CreateUserText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.CreateUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_EditProfileText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.EditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_HelpPageText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_InstructionText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола:.
        /// </summary>
        internal static string ChangePassword1Resource1_NewPasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.NewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новата парола е задължителна..
        /// </summary>
        internal static string ChangePassword1Resource1_NewPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.NewPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_PasswordHintText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.PasswordHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола:.
        /// </summary>
        internal static string ChangePassword1Resource1_PasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_PasswordRecoveryText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.PasswordRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължителна..
        /// </summary>
        internal static string ChangePassword1Resource1_PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата Ви беше сменена!.
        /// </summary>
        internal static string ChangePassword1Resource1_SuccessText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на паролата завършена!.
        /// </summary>
        internal static string ChangePassword1Resource1_SuccessTitleText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.SuccessTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име:.
        /// </summary>
        internal static string ChangePassword1Resource1_UserNameLabelText {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.UserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име е задължително..
        /// </summary>
        internal static string ChangePassword1Resource1_UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword1Resource1.UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        internal static string ChangePassword2Resource1_CancelButtonText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Променете парола.
        /// </summary>
        internal static string ChangePassword2Resource1_ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата не е правилна или Нова парола невалидна. Минимална дължина на нова парола: {0}. Не-буквено-цифрови знаци се изискват: {1}..
        /// </summary>
        internal static string ChangePassword2Resource1_ChangePasswordFailureText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ChangePasswordFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на парола.
        /// </summary>
        internal static string ChangePassword2Resource1_ChangePasswordTitleText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ChangePasswordTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете паролата:.
        /// </summary>
        internal static string ChangePassword2Resource1_ConfirmNewPasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ConfirmNewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдената нова парола трябва да съответства на нововъведената на парола..
        /// </summary>
        internal static string ChangePassword2Resource1_ConfirmPasswordCompareErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ConfirmPasswordCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаването на новата парола е задължително. .
        /// </summary>
        internal static string ChangePassword2Resource1_ConfirmPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ConfirmPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължете.
        /// </summary>
        internal static string ChangePassword2Resource1_ContinueButtonText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_CreateUserText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.CreateUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_EditProfileText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.EditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_HelpPageText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_InstructionText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола:.
        /// </summary>
        internal static string ChangePassword2Resource1_NewPasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.NewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новата парола е задължителна..
        /// </summary>
        internal static string ChangePassword2Resource1_NewPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.NewPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_PasswordHintText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.PasswordHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола:.
        /// </summary>
        internal static string ChangePassword2Resource1_PasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_PasswordRecoveryText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.PasswordRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължителна..
        /// </summary>
        internal static string ChangePassword2Resource1_PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата Ви беше сменена!.
        /// </summary>
        internal static string ChangePassword2Resource1_SuccessText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешна промяна на парола..
        /// </summary>
        internal static string ChangePassword2Resource1_SuccessTitleText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.SuccessTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePassword2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име:.
        /// </summary>
        internal static string ChangePassword2Resource1_UserNameLabelText {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.UserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име е задължително..
        /// </summary>
        internal static string ChangePassword2Resource1_UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ChangePassword2Resource1.UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string CompleteWizardStepResource1_Title {
            get {
                return ResourceManager.GetString("CompleteWizardStepResource1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_Answer {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговор за сигурност:.
        /// </summary>
        internal static string CreateUserWizard1Resource1_AnswerLabelText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.AnswerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изисква се отговор сигурност..
        /// </summary>
        internal static string CreateUserWizard1Resource1_AnswerRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.AnswerRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        internal static string CreateUserWizard1Resource1_CancelButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът Ви е създаден успешно..
        /// </summary>
        internal static string CreateUserWizard1Resource1_CompleteSuccessText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.CompleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата и потвърждение на паролата трябва да съвпадат..
        /// </summary>
        internal static string CreateUserWizard1Resource1_ConfirmPasswordCompareErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.ConfirmPasswordCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърди парола:.
        /// </summary>
        internal static string CreateUserWizard1Resource1_ConfirmPasswordLabelText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.ConfirmPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение на паролата е задължително..
        /// </summary>
        internal static string CreateUserWizard1Resource1_ConfirmPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.ConfirmPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължете.
        /// </summary>
        internal static string CreateUserWizard1Resource1_ContinueButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създайте потребител.
        /// </summary>
        internal static string CreateUserWizard1Resource1_CreateUserButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.CreateUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адресът на електронната поща, която сте въвели е вече в употреба. Моля, въведете друг адрес на електронна поща..
        /// </summary>
        internal static string CreateUserWizard1Resource1_DuplicateEmailErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.DuplicateEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете различно потребителско име..
        /// </summary>
        internal static string CreateUserWizard1Resource1_DuplicateUserNameErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.DuplicateUserNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_EditProfileText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.EditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string CreateUserWizard1Resource1_EmailLabelText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.EmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е задължителен..
        /// </summary>
        internal static string CreateUserWizard1Resource1_EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край.
        /// </summary>
        internal static string CreateUserWizard1Resource1_FinishCompleteButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.FinishCompleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предишен.
        /// </summary>
        internal static string CreateUserWizard1Resource1_FinishPreviousButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.FinishPreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_HeaderText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_HelpPageText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_InstructionText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете различен отговор сигурност..
        /// </summary>
        internal static string CreateUserWizard1Resource1_InvalidAnswerErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.InvalidAnswerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете валиден имейл адрес..
        /// </summary>
        internal static string CreateUserWizard1Resource1_InvalidEmailErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.InvalidEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length minimum: {0}. Non-alphanumeric characters required: {1}..
        /// </summary>
        internal static string CreateUserWizard1Resource1_InvalidPasswordErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.InvalidPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете друг въпрос за сигурност..
        /// </summary>
        internal static string CreateUserWizard1Resource1_InvalidQuestionErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.InvalidQuestionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_PasswordHintText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.PasswordHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола:.
        /// </summary>
        internal static string CreateUserWizard1Resource1_PasswordLabelText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължителна..
        /// </summary>
        internal static string CreateUserWizard1Resource1_PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_Question {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въпрос за сигурност..
        /// </summary>
        internal static string CreateUserWizard1Resource1_QuestionLabelText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въпросът за сигурност е задължителен..
        /// </summary>
        internal static string CreateUserWizard1Resource1_QuestionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.QuestionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_SkipLinkText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.SkipLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следващ.
        /// </summary>
        internal static string CreateUserWizard1Resource1_StartNextButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.StartNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следващ.
        /// </summary>
        internal static string CreateUserWizard1Resource1_StepNextButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.StepNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предишен.
        /// </summary>
        internal static string CreateUserWizard1Resource1_StepPreviousButtonText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.StepPreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserWizard1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът Ви не е създаден. Моля, опитайте отново..
        /// </summary>
        internal static string CreateUserWizard1Resource1_UnknownErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име:.
        /// </summary>
        internal static string CreateUserWizard1Resource1_UserNameLabelText {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.UserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име е задължително..
        /// </summary>
        internal static string CreateUserWizard1Resource1_UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateUserWizard1Resource1.UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запишете се за новият Ви профил.
        /// </summary>
        internal static string CreateUserWizardStepResource1_Title {
            get {
                return ResourceManager.GetString("CreateUserWizardStepResource1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Image1Resource1_AlternateText {
            get {
                return ResourceManager.GetString("Image1Resource1.AlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Image1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("Image1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕЛЕКТРОННА КНИЖАРНИЦА.
        /// </summary>
        internal static string Label1Resource2_Text {
            get {
                return ResourceManager.GetString("Label1Resource2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на потребител.
        /// </summary>
        internal static string LinkButton3Resource1_Text {
            get {
                return ResourceManager.GetString("LinkButton3Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LinkButton3Resource1_ToolTip {
            get {
                return ResourceManager.GetString("LinkButton3Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login1Resource1_CreateUserText {
            get {
                return ResourceManager.GetString("Login1Resource1.CreateUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешен потребител или парола. Моля опитайте отново!.
        /// </summary>
        internal static string Login1Resource1_FailureText {
            get {
                return ResourceManager.GetString("Login1Resource1.FailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login1Resource1_HelpPageText {
            get {
                return ResourceManager.GetString("Login1Resource1.HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login1Resource1_InstructionText {
            get {
                return ResourceManager.GetString("Login1Resource1.InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Login1Resource1_LoginButtonText {
            get {
                return ResourceManager.GetString("Login1Resource1.LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола:.
        /// </summary>
        internal static string Login1Resource1_PasswordLabelText {
            get {
                return ResourceManager.GetString("Login1Resource1.PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login1Resource1_PasswordRecoveryText {
            get {
                return ResourceManager.GetString("Login1Resource1.PasswordRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължителна..
        /// </summary>
        internal static string Login1Resource1_PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Login1Resource1.PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме следващия път..
        /// </summary>
        internal static string Login1Resource1_RememberMeText {
            get {
                return ResourceManager.GetString("Login1Resource1.RememberMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login1Resource1_TitleText {
            get {
                return ResourceManager.GetString("Login1Resource1.TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("Login1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име:.
        /// </summary>
        internal static string Login1Resource1_UserNameLabelText {
            get {
                return ResourceManager.GetString("Login1Resource1.UserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        internal static string Login1Resource1_UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Login1Resource1.UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string LoginName1Resource1_FormatString {
            get {
                return ResourceManager.GetString("LoginName1Resource1.FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoginName1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("LoginName1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string LoginName2Resource1_FormatString {
            get {
                return ResourceManager.GetString("LoginName2Resource1.FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoginName2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("LoginName2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string LoginStatus1Resource1_LoginText {
            get {
                return ResourceManager.GetString("LoginStatus1Resource1.LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        internal static string LoginStatus1Resource1_LogoutText {
            get {
                return ResourceManager.GetString("LoginStatus1Resource1.LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoginStatus1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("LoginStatus1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string LoginStatus2Resource1_LoginText {
            get {
                return ResourceManager.GetString("LoginStatus2Resource1.LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        internal static string LoginStatus2Resource1_LogoutText {
            get {
                return ResourceManager.GetString("LoginStatus2Resource1.LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoginStatus2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("LoginStatus2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll down.
        /// </summary>
        internal static string Menu1Resource1_ScrollDownText {
            get {
                return ResourceManager.GetString("Menu1Resource1.ScrollDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up.
        /// </summary>
        internal static string Menu1Resource1_ScrollUpText {
            get {
                return ResourceManager.GetString("Menu1Resource1.ScrollUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Navigation Links.
        /// </summary>
        internal static string Menu1Resource1_SkipLinkText {
            get {
                return ResourceManager.GetString("Menu1Resource1.SkipLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Menu1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("Menu1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        internal static string PassForgottenResource1_Text {
            get {
                return ResourceManager.GetString("PassForgottenResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassForgottenResource1_ToolTip {
            get {
                return ResourceManager.GetString("PassForgottenResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговор:.
        /// </summary>
        internal static string PasswordRecovery1Resource1_AnswerLabelText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.AnswerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорът е задължителен..
        /// </summary>
        internal static string PasswordRecovery1Resource1_AnswerRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.AnswerRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашия опит да извлечете паролата си не е бил успешен. Моля, опитайте отново..
        /// </summary>
        internal static string PasswordRecovery1Resource1_GeneralFailureText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.GeneralFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecovery1Resource1_HelpPageText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорът Ви не е правилен .Моля опитайте отново..
        /// </summary>
        internal static string PasswordRecovery1Resource1_QuestionFailureText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.QuestionFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорете на следващия въпрос за да получите паролата си..
        /// </summary>
        internal static string PasswordRecovery1Resource1_QuestionInstructionText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.QuestionInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въпрос:.
        /// </summary>
        internal static string PasswordRecovery1Resource1_QuestionLabelText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение на потребителя..
        /// </summary>
        internal static string PasswordRecovery1Resource1_QuestionTitleText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.QuestionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане.
        /// </summary>
        internal static string PasswordRecovery1Resource1_SubmitButtonText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата Ви беше изпратена..
        /// </summary>
        internal static string PasswordRecovery1Resource1_SuccessText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecovery1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecovery1Resource1_UserName {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не успяхме да достъпим вашата информация.Моля опитайте отново..
        /// </summary>
        internal static string PasswordRecovery1Resource1_UserNameFailureText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.UserNameFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете своето потребителско име, за да получите паролата си..
        /// </summary>
        internal static string PasswordRecovery1Resource1_UserNameInstructionText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.UserNameInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име:.
        /// </summary>
        internal static string PasswordRecovery1Resource1_UserNameLabelText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.UserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име е задължително..
        /// </summary>
        internal static string PasswordRecovery1Resource1_UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравихте паролата си?.
        /// </summary>
        internal static string PasswordRecovery1Resource1_UserNameTitleText {
            get {
                return ResourceManager.GetString("PasswordRecovery1Resource1.UserNameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &gt; .
        /// </summary>
        internal static string SiteMapPath1Resource1_PathSeparator {
            get {
                return ResourceManager.GetString("SiteMapPath1Resource1.PathSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Navigation Links.
        /// </summary>
        internal static string SiteMapPath1Resource1_SkipLinkText {
            get {
                return ResourceManager.GetString("SiteMapPath1Resource1.SkipLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SiteMapPath1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("SiteMapPath1Resource1.ToolTip", resourceCulture);
            }
        }
    }
}
